import { Spec } from "../types/spec.js";

export interface GeneratedFile {
  path: string;
  content: string;
}

export class FileGenerator {
  generateFiles(spec: Spec): GeneratedFile[] {
    const files: GeneratedFile[] = [];

    files.push(...this.generateGitHubFiles(spec));
    files.push(...this.generateConfigFiles(spec));
    files.push(...this.generateDocumentation(spec));

    return files;
  }

  private generateGitHubFiles(spec: Spec): GeneratedFile[] {
    return [
      {
        path: ".github/dependabot.yml",
        content: this.generateDependabot(spec),
      },
      {
        path: ".github/CODEOWNERS",
        content: this.generateCodeOwners(),
      },
    ];
  }

  private generateConfigFiles(spec: Spec): GeneratedFile[] {
    return [
      {
        path: ".editorconfig",
        content: this.generateEditorConfig(),
      },
      {
        path: ".gitattributes",
        content: this.generateGitAttributes(),
      },
    ];
  }

  private generateDocumentation(spec: Spec): GeneratedFile[] {
    return [
      {
        path: "README.md",
        content: this.generateReadme(spec),
      },
      {
        path: "CONTRIBUTING.md",
        content: this.generateContributing(spec),
      },
      {
        path: "SECURITY.md",
        content: this.generateSecurity(spec),
      },
      {
        path: "CHANGELOG.md",
        content: "# Changelog\n\nAll notable changes to this project will be documented in this file.\n",
      },
    ];
  }

  private generateDependabot(spec: Spec): string {
    const ecosystems = spec.project.language === "python" ? "pip" : "npm";
    return `version: 2
updates:
  - package-ecosystem: "${ecosystems}"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
`;
  }

  private generateCodeOwners(): string {
    return `# CODEOWNERS
# See: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

# Specify default code owners for the repo
# * @username

# Assign specific paths to team members
# /src/  @team-name
# .github/workflows/ @devops-team
`;
  }

  private generateEditorConfig(): string {
    return `root = true

[*]
charset = utf-8
end_of_line = lf
insert_final_newline = true
trim_trailing_whitespace = true

[*.{json,yaml,yml}]
indent_style = space
indent_size = 2

[*.py]
indent_style = space
indent_size = 4
`;
  }

  private generateGitAttributes(): string {
    return `* text=auto
*.js text eol=lf
*.ts text eol=lf
*.json text eol=lf
*.md text eol=lf
`;
  }

  private generateReadme(spec: Spec): string {
    return `# Project

> Automatically generated by [RepoForge](https://github.com/repoforge/repoforge)

## Overview

This is a \`${spec.project.type}\` project written in \`${spec.project.language}\`.

## Development

\`\`\`bash
npm install
npm run dev
\`\`\`

## Testing

\`\`\`bash
npm test
\`\`\`

## License

MIT
`;
  }

  private generateContributing(spec: Spec): string {
    return `# Contributing

## Code Standards

This repository enforces strict code standards via CI.

### Requirements

- All tests must pass
- Type checking must succeed
- Linting must pass
- Security scans must pass

## Process

1. Create a feature branch
2. Make your changes
3. Ensure all checks pass
4. Submit a pull request

## Conventional Commits

We use [Conventional Commits](https://www.conventionalcommits.org/) for commit messages.

\`\`\`
<type>(<scope>): <subject>
\`\`\`

Types: \`feat\`, \`fix\`, \`docs\`, \`test\`, \`refactor\`, \`perf\`, \`ci\`
`;
  }

  private generateSecurity(spec: Spec): string {
    return `# Security Policy

## Reporting a Vulnerability

If you discover a security vulnerability, please email **[ADD YOUR SECURITY CONTACT]** instead of using the issue tracker.

Do not open public issues for security vulnerabilities.

## Supported Versions

Only the latest version is supported with security updates.

## Security Features

- Automated dependency scanning (Dependabot)
- Secret scanning enabled
- SAST via CodeQL
- License compliance checking

## Security Best Practices

- Keep dependencies up to date
- Review dependabot PRs promptly
- Address security alerts immediately
- Use branch protection rules
- Require status checks before merge

See [CONTRIBUTING.md](./CONTRIBUTING.md) for development guidelines.
`;
  }
}
